name: "Fastify Starter: QA"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # paths:
    #   - "backend/**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: fastify-auth-template-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit
